// ReactNotes/coderwhy/04.React脚手架/01-test-react/src/App.js
import React, { Component } from 'react';

class HYTestCpn extends Component {
    render() {
        return <h2>HYTestCpn</h2>
    }

    componentWillUnmount() {
        console.log("HYTestCpn componentWillUnmount");
    }
}

export default class App extends Component {
    constructor(props) {
        super(props);
        this.state = {
            counter: 0
        }
        console.log("调用constructor方法");
    }

    componentDidMount() {
        console.log("调用componentDidMount方法");
    }
    
    componentDidUpdate() {
        console.log("调用componentDidUpdate方法");
    }
    
    componentWillUnmount() {
        console.log("调用componentWillUnmount方法");
    }

    render() {
        console.log("调用render方法")
        return (
            <div>
              <h2>当前计数: {this.state.counter}</h2>
              {this.state.counter <= 5 && <HYTestCpn/>}
              <button onClick={e => this.increment()}>+1</button>
            </div>
        )
    }

    increment() {
        this.setState({
            counter: this.state.counter + 1
        })
    }
}

// 函数组件
// export default function App() {
//     return <div>Hello World</div>
// }

// 深入Vue3+TypeScript技术栈/01-Learn-Vue3/02-composition-api/src/02_composition_api的基本使用/App.vue
<template>
  <div>
    <h2>当前计数：{{counter}}</h2>
    <button @click="increment">+1</button>
  </div>
</template>

<script>
import { ref } from 'vue'

export default {
  name: "App",
  setup() {

    let counter = ref(100);

    const increment = () => {
      counter.value++;
      console.log(counter.value)
    }

    return {
      counter,
      increment
    }
  }
}
</script>

<style scoped>

</style>
